#![doc = include_str!("../README.md")]

pub mod axis;
pub mod bounding_box;
pub mod common;
pub mod cone;
pub mod csg;
pub mod cube;
pub mod cylinder;
pub mod filter;
pub mod function;
pub mod hit;
pub mod matrix;
pub mod mesh;
pub mod obj;
pub mod path;
pub mod plane;
pub mod ray;
pub mod scene;
pub mod shape;
pub mod sphere;
pub mod stl;
pub mod tree;
pub mod triangle;
pub mod util;
pub mod vector;

// Re-exports for convenient access
pub use axis::Axis;
pub use bounding_box::Box;
pub use cone::{Cone, ConeTexture, new_transformed_cone};
pub use csg::{BooleanShape, Op, new_difference, new_intersection};
pub use cube::{Cube, CubeTexture};
pub use cylinder::{Cylinder, CylinderTexture, new_transformed_cylinder};
pub use filter::{ClipFilter, Filter};
pub use function::{Direction, Function, FunctionTexture};
pub use hit::Hit;
pub use matrix::Matrix;
pub use mesh::Mesh;
pub use obj::load_obj;
pub use path::{Path, Paths};
pub use plane::Plane;
pub use ray::Ray;
pub use scene::Scene;
pub use shape::{EmptyShape, RenderArgs, Shape, TransformedShape};
pub use sphere::{Sphere, SphereTexture, lat_lng_to_xyz};
pub use stl::{load_binary_stl, load_stl, save_binary_stl};
pub use tree::Tree;
pub use triangle::Triangle;
pub use util::{degrees, median, radians};
pub use vector::Vector;
